version: "3"
services:
  pay-app:
    image: payment-service-app
    build: ./
    ports:
      - "8092:8080"
    container_name: payment-container
    links:
      - mongodb:app_db
    networks:
      - shared-net


  mongodb:
    image: mongo
    ports:
      - "27019:27017"
    container_name: mongo-server-2
    networks:
      - shared-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express-ui-2
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge